//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Department { get; set; }
        public string MailID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<long> Phone { get; set; }
        public string Address { get; set; }
        public Nullable<long> Salary { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
